name = "Ecp"
uuid = "b9fd3632-ceed-4cc4-b03d-19a0f4218fbe"
authors = ["Jakub Malinowski <jakubbmalinowski@gmail.com>"]
version = "0.1.0"

[deps]
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
